provider: zhipu
base_url: http://192.168.32.15:39999/v1
api_key: ${ZHIPU_API_KEY}
models_cache:
    - 01-ai/yi-large
    - LongCat-Flash-Chat
    - LongCat-Flash-Thinking-2601
    - abacusai/dracarys-llama-3.1-70b-instruct
    - adept/fuyu-8b
    - ai21labs/jamba-1.5-large-instruct
    - ai21labs/jamba-1.5-mini-instruct
    - aisingapore/sea-lion-7b-instruct
    - baai/bge-m3
    - baichuan-inc/baichuan2-13b-chat
    - bigcode/starcoder2-15b
    - bigcode/starcoder2-7b
    - bytedance/seed-oss-36b-instruct
    - databricks/dbrx-instruct
    - deepseek-ai/deepseek-coder-6.7b-instruct
    - deepseek-ai/deepseek-r1-distill-llama-8b
    - deepseek-ai/deepseek-r1-distill-qwen-14b
    - deepseek-ai/deepseek-r1-distill-qwen-32b
    - deepseek-ai/deepseek-r1-distill-qwen-7b
    - deepseek-ai/deepseek-v3.1
    - deepseek-ai/deepseek-v3.1-terminus
    - deepseek-ai/deepseek-v3.2
    - deepseek-r1
    - deepseek-v3
    - deepseek-v3.1
    - deepseek-v3.2
    - deepseek-v3.2-chat
    - deepseek-v3.2-reasoner
    - gemini-fast
    - glm-4.6
    - glm-4.7
    - google/codegemma-1.1-7b
    - google/codegemma-7b
    - google/deplot
    - google/gemma-2-27b-it
    - google/gemma-2-2b-it
    - google/gemma-2-9b-it
    - google/gemma-2b
    - google/gemma-3-12b-it
    - google/gemma-3-1b-it
    - google/gemma-3-27b-it
    - google/gemma-3-4b-it
    - google/gemma-3n-e2b-it
    - google/gemma-3n-e4b-it
    - google/gemma-7b
    - google/paligemma
    - google/recurrentgemma-2b
    - google/shieldgemma-9b
    - gotocompany/gemma-2-9b-cpt-sahabatai-instruct
    - gpt-4.1
    - gpt-5
    - gpt-5.1
    - gpt-5.1-codex
    - gpt-5.1-codex-max
    - gpt-5.1-codex-max-openai-compact
    - gpt-5.1-codex-mini
    - gpt-5.1-codex-mini-openai-compact
    - gpt-5.1-codex-openai-compact
    - gpt-5.1-openai-compact
    - gpt-5.2
    - gpt-5.2-codex
    - gpt-5.2-codex-openai-compact
    - gpt-5.2-openai-compact
    - ibm/granite-3.0-3b-a800m-instruct
    - ibm/granite-3.0-8b-instruct
    - ibm/granite-3.3-8b-instruct
    - ibm/granite-34b-code-instruct
    - ibm/granite-8b-code-instruct
    - ibm/granite-guardian-3.0-8b
    - iflow-rome-30ba3b
    - igenius/colosseum_355b_instruct_16k
    - igenius/italia_10b_instruct_16k
    - institute-of-science-tokyo/llama-3.1-swallow-70b-instruct-v0.1
    - institute-of-science-tokyo/llama-3.1-swallow-8b-instruct-v0.1
    - kimi-k2
    - kimi-k2-0905
    - kimi-k2-thinking
    - marin/marin-8b-instruct
    - mediatek/breeze-7b-instruct
    - meta/codellama-70b
    - meta/llama-3.1-405b-instruct
    - meta/llama-3.1-70b-instruct
    - meta/llama-3.1-8b-instruct
    - meta/llama-3.2-11b-vision-instruct
    - meta/llama-3.2-1b-instruct
    - meta/llama-3.2-3b-instruct
    - meta/llama-3.2-90b-vision-instruct
    - meta/llama-3.3-70b-instruct
    - meta/llama-4-maverick-17b-128e-instruct
    - meta/llama-4-scout-17b-16e-instruct
    - meta/llama-guard-4-12b
    - meta/llama2-70b
    - meta/llama3-70b-instruct
    - meta/llama3-8b-instruct
    - microsoft/kosmos-2
    - microsoft/phi-3-medium-128k-instruct
    - microsoft/phi-3-medium-4k-instruct
    - microsoft/phi-3-mini-128k-instruct
    - microsoft/phi-3-mini-4k-instruct
    - microsoft/phi-3-small-128k-instruct
    - microsoft/phi-3-small-8k-instruct
    - microsoft/phi-3-vision-128k-instruct
    - microsoft/phi-3.5-mini-instruct
    - microsoft/phi-3.5-moe-instruct
    - microsoft/phi-3.5-vision-instruct
    - microsoft/phi-4-mini-flash-reasoning
    - microsoft/phi-4-mini-instruct
    - microsoft/phi-4-multimodal-instruct
    - minimax-m2
    - minimax-m2.1
    - minimaxai/minimax-m2
    - minimaxai/minimax-m2.1
    - mistral-large
    - mistralai/codestral-22b-instruct-v0.1
    - mistralai/devstral-2-123b-instruct-2512
    - mistralai/magistral-small-2506
    - mistralai/mamba-codestral-7b-v0.1
    - mistralai/mathstral-7b-v0.1
    - mistralai/ministral-14b-instruct-2512
    - mistralai/mistral-7b-instruct-v0.2
    - mistralai/mistral-7b-instruct-v0.3
    - mistralai/mistral-large
    - mistralai/mistral-large-2-instruct
    - mistralai/mistral-large-3-675b-instruct-2512
    - mistralai/mistral-medium-3-instruct
    - mistralai/mistral-nemotron
    - mistralai/mistral-small-24b-instruct
    - mistralai/mistral-small-3.1-24b-instruct-2503
    - mistralai/mixtral-8x22b-instruct-v0.1
    - mistralai/mixtral-8x22b-v0.1
    - mistralai/mixtral-8x7b-instruct-v0.1
    - moonshotai/kimi-k2-instruct
    - moonshotai/kimi-k2-instruct-0905
    - moonshotai/kimi-k2-thinking
    - moonshotai/kimi-k2.5
    - nv-mistralai/mistral-nemo-12b-instruct
    - nvidia/cosmos-reason2-8b
    - nvidia/embed-qa-4
    - nvidia/llama-3.1-nemoguard-8b-content-safety
    - nvidia/llama-3.1-nemoguard-8b-topic-control
    - nvidia/llama-3.1-nemotron-51b-instruct
    - nvidia/llama-3.1-nemotron-70b-instruct
    - nvidia/llama-3.1-nemotron-70b-reward
    - nvidia/llama-3.1-nemotron-nano-4b-v1.1
    - nvidia/llama-3.1-nemotron-nano-8b-v1
    - nvidia/llama-3.1-nemotron-nano-vl-8b-v1
    - nvidia/llama-3.1-nemotron-safety-guard-8b-v3
    - nvidia/llama-3.1-nemotron-ultra-253b-v1
    - nvidia/llama-3.2-nemoretriever-1b-vlm-embed-v1
    - nvidia/llama-3.2-nemoretriever-300m-embed-v1
    - nvidia/llama-3.2-nemoretriever-300m-embed-v2
    - nvidia/llama-3.2-nv-embedqa-1b-v1
    - nvidia/llama-3.2-nv-embedqa-1b-v2
    - nvidia/llama-3.3-nemotron-super-49b-v1
    - nvidia/llama-3.3-nemotron-super-49b-v1.5
    - nvidia/llama3-chatqa-1.5-70b
    - nvidia/llama3-chatqa-1.5-8b
    - nvidia/mistral-nemo-minitron-8b-8k-instruct
    - nvidia/mistral-nemo-minitron-8b-base
    - nvidia/nemoretriever-parse
    - nvidia/nemotron-3-nano-30b-a3b
    - nvidia/nemotron-4-340b-instruct
    - nvidia/nemotron-4-340b-reward
    - nvidia/nemotron-4-mini-hindi-4b-instruct
    - nvidia/nemotron-content-safety-reasoning-4b
    - nvidia/nemotron-mini-4b-instruct
    - nvidia/nemotron-nano-12b-v2-vl
    - nvidia/nemotron-nano-3-30b-a3b
    - nvidia/nemotron-parse
    - nvidia/neva-22b
    - nvidia/nv-embed-v1
    - nvidia/nv-embedcode-7b-v1
    - nvidia/nv-embedqa-e5-v5
    - nvidia/nv-embedqa-mistral-7b-v2
    - nvidia/nvclip
    - nvidia/nvidia-nemotron-nano-9b-v2
    - nvidia/riva-translate-4b-instruct
    - nvidia/riva-translate-4b-instruct-v1.1
    - nvidia/streampetr
    - nvidia/usdcode-llama-3.1-70b-instruct
    - nvidia/vila
    - openai/gpt-oss-120b
    - openai/gpt-oss-20b
    - opengpt-x/teuken-7b-instruct-commercial-v0.4
    - qwen/qwen2-7b-instruct
    - qwen/qwen2.5-7b-instruct
    - qwen/qwen2.5-coder-32b-instruct
    - qwen/qwen2.5-coder-7b-instruct
    - qwen/qwen3-235b-a22b
    - qwen/qwen3-coder-480b-a35b-instruct
    - qwen/qwen3-next-80b-a3b-instruct
    - qwen/qwen3-next-80b-a3b-thinking
    - qwen/qwq-32b
    - qwen3-235b
    - qwen3-235b-a22b-instruct
    - qwen3-235b-a22b-thinking-2507
    - qwen3-32b
    - qwen3-coder-flash
    - qwen3-coder-plus
    - qwen3-max
    - qwen3-max-preview
    - qwen3-vl-plus
    - rakuten/rakutenai-7b-chat
    - rakuten/rakutenai-7b-instruct
    - sarvamai/sarvam-m
    - snowflake/arctic-embed-l
    - speakleash/bielik-11b-v2.3-instruct
    - speakleash/bielik-11b-v2.6-instruct
    - stepfun-ai/step-3.5-flash
    - stockmark/stockmark-2-100b-instruct
    - thudm/chatglm3-6b
    - tiiuae/falcon3-7b-instruct
    - tokyotech-llm/llama-3-swallow-70b-instruct-v0.1
    - tstars2.0
    - upstage/solar-10.7b-instruct
    - utter-project/eurollm-9b-instruct
    - vision-model
    - writer/palmyra-creative-122b
    - writer/palmyra-fin-70b-32k
    - writer/palmyra-med-70b
    - writer/palmyra-med-70b-32k
    - yentinglin/llama-3-taiwan-70b-instruct
    - z-ai/glm4.7
    - zyphra/zamba2-7b-instruct
updated_at: "2026-02-05T18:10:50Z"
